### ISSUE TITLE
django-gatekeeper cannot be registered on model already containing a content_type field

### ISSUE THREAD

**Issue by davej** [sunlightlabs/django-gatekeeper#1]
Django raises 'ambiguous column name', if you register django-gatekeeper on a model which already contains a content_type field.

This is particularly an issue when trying to add moderation to models contained in third-party apps, where I don't want to rename the model fields.

**Comment by jamesturk** [comment]
add table reference to where clause, losed by 44deba4de08e02bd05681ded9d348ff5311d73e0
